VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "CPRDFiles"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'<comment>
' <summary>
' This object holds data that will be written to a line in a file.</summary>
'</comment>

Option Explicit

Public Field1 As String
Public Field2 As String
Public Field3 As String
Public Field4 As String
Public Field5 As String
Public Field6 As String
Public Field7 As String
Public Field8 As String
Public Field9 As String
Public Field10 As String
Public Field11 As String
Public Field12 As String
Public Field13 As String
Public Field14 As String
Public Field15 As String
Public Field16 As String
Public Field17 As String
Public Field18 As String
Public Field19 As String
Public Field20 As String
' DW increasing # of columns from 20 to 30 based on client supplied data
Public Field21 As String
Public Field22 As String
Public Field23 As String
Public Field24 As String
Public Field25 As String
Public Field26 As String
Public Field27 As String
Public Field28 As String
Public Field29 As String
Public Field30 As String
